#!/bin/bash
set -euo pipefail

usage() {
  cat <<'USAGE_EOF'
Usage: scripts/maintenance-triage.sh [--json] [--heartbeat] [--inbox PATH]
USAGE_EOF
}

output_mode="text"
heartbeat_mode=0
inbox_path=".ai/harness/triage/inbox.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --json)
      output_mode="json"
      shift
      ;;
    --heartbeat)
      heartbeat_mode=1
      shift
      ;;
    --inbox)
      [[ -n "${2:-}" ]] || { echo "maintenance-triage: --inbox requires a value" >&2; exit 2; }
      inbox_path="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

json_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  value="${value//$'\t'/\\t}"
  printf '%s' "$value"
}

heartbeat_plus_14_days() {
  date -v+14d '+%Y-%m-%d' 2>/dev/null || date -d '+14 days' '+%Y-%m-%d' 2>/dev/null || date '+%Y-%m-%d'
}

heartbeat_fallback_next_task() {
  local sprints_dir="${REPO_HARNESS_HEARTBEAT_SPRINT_DIR:-tasks/sprints}"
  local sprint_file status task

  [[ -d "$sprints_dir" ]] || return 1

  for sprint_file in $(find "$sprints_dir" -maxdepth 1 -type f -name '*.sprint.md' 2>/dev/null | sort -r); do
    status="$(awk '/^\> \*\*Status\*\*:/ {sub(/^.*\> \*\*Status\*\*: */, ""); gsub(/\r/, ""); print; exit}' "$sprint_file" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g')"
    case "$status" in
      Approved|Executing) ;;
      *) continue ;;
    esac
    task="$(
      awk -F '|' '
        /^## Backlog[[:space:]]*$/ { in_section = 1; next }
        in_section && /^## / { exit }
        !in_section { next }
        /^\|[[:space:]]*[0-9]+[[:space:]]*\|/ {
          status = $3
          task = $4
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", status)
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", task)
          if (status == "[ ]") {
            print task
            exit
          }
        }
      ' "$sprint_file"
    )"
    if [[ -n "$task" ]]; then
      printf '%s' "$task"
      return 0
    fi
  done

  return 1
}

run_heartbeat_probe() {
  local command="$1"
  local output status

  set +e
  output="$(bash -lc "$command" 2>&1)"
  status=$?
  set -e

  printf '%s\t%s\n%s' "$status" "$(printf '%s' "$output" | wc -c | tr -d ' ')" "$output"
}

heartbeat_mode_run() {
  local workflow_cmd sprint_cmd drift_dir timestamp adoption_date
  local workflow_probe workflow_status workflow_output
  local sprint_probe sprint_status sprint_output next_task
  local drift_count drift_items inbox_dir

  workflow_cmd="${REPO_HARNESS_HEARTBEAT_WORKFLOW_CMD:-bash scripts/check-task-workflow.sh --strict}"
  sprint_cmd="${REPO_HARNESS_HEARTBEAT_SPRINT_CMD:-bash scripts/sprint-backlog.sh next}"
  drift_dir="${REPO_HARNESS_HEARTBEAT_DRIFT_DIR:-docs/architecture/requests}"
  if [[ -z "${REPO_HARNESS_BRAIN_ROOT:-}" ]]; then
    export REPO_HARNESS_BRAIN_ROOT="${HOME}/Library/Mobile Documents/com~apple~CloudDocs/brain"
  fi
  timestamp="$(date '+%Y-%m-%d %H:%M:%S %z')"
  adoption_date="$(heartbeat_plus_14_days)"

  workflow_probe="$(run_heartbeat_probe "$workflow_cmd")"
  workflow_status="$(printf '%s\n' "$workflow_probe" | head -n 1 | cut -f1)"
  workflow_output="$(printf '%s\n' "$workflow_probe" | sed '1d')"

  sprint_probe="$(run_heartbeat_probe "$sprint_cmd")"
  sprint_status="$(printf '%s\n' "$sprint_probe" | head -n 1 | cut -f1)"
  sprint_output="$(printf '%s\n' "$sprint_probe" | sed '1d')"
  next_task="$(printf '%s\n' "$sprint_output" | sed -nE 's/^task:[[:space:]]*//p' | head -n 1)"
  if [[ -z "$next_task" ]]; then
    next_task="$(heartbeat_fallback_next_task || true)"
  fi
  if [[ -z "$next_task" ]]; then
    next_task="(unavailable)"
  fi

  drift_count=0
  drift_items=""
  if [[ -d "$drift_dir" ]]; then
    drift_count="$(find "$drift_dir" -maxdepth 1 -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
    drift_items="$(find "$drift_dir" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort | sed 's#^\./##' | head -n 10)"
  fi

  inbox_dir="$(dirname "$inbox_path")"
  mkdir -p "$inbox_dir"
  if [[ ! -f "$inbox_path" ]]; then
    {
      echo "# Triage Inbox"
      echo
      echo "Generated by \`scripts/maintenance-triage.sh --heartbeat\`. Entries are append-only triage snapshots; humans decide adoption."
    } > "$inbox_path"
  fi

  {
    echo
    echo "## Heartbeat ${timestamp}"
    echo
    echo "- Source: \`scripts/maintenance-triage.sh --heartbeat\`"
    echo "- Workflow check: $([[ "$workflow_status" == "0" ]] && printf 'pass' || printf 'fail')"
    echo "- Sprint next: ${next_task}"
    echo "- Drift requests: ${drift_count}"
    echo "- Adoption review: scheduled for ${adoption_date}"
    echo
    echo "### Workflow Output"
    echo
    printf '%s\n' "$workflow_output" | sed 's/^/    /' | head -n 20
    echo
    echo "### Sprint Next Output"
    echo
    printf '%s\n' "$sprint_output" | sed 's/^/    /' | head -n 20
    if [[ "$drift_count" != "0" ]]; then
      echo
      echo "### Drift Requests"
      echo
      printf '%s\n' "$drift_items" | sed 's/^/- /'
    fi
  } >> "$inbox_path"

  if [[ "$output_mode" == "json" ]]; then
    printf '{"inbox":"%s","workflow_status":%s,"sprint_status":%s,"next_task":"%s","drift_requests":%s,"adoption_review":"%s"}\n' \
      "$(json_escape "$inbox_path")" \
      "$workflow_status" \
      "$sprint_status" \
      "$(json_escape "$next_task")" \
      "$drift_count" \
      "$(json_escape "$adoption_date")"
  else
    echo "[Heartbeat] wrote triage entry: $inbox_path"
    echo "[Heartbeat] workflow=$([[ "$workflow_status" == "0" ]] && printf 'pass' || printf 'fail') sprint_next=${next_task} drift_requests=${drift_count} adoption_review=${adoption_date}"
  fi
}

if [[ "$heartbeat_mode" -eq 1 ]]; then
  heartbeat_mode_run
  exit 0
fi

if [[ ! -f "tasks/lessons.md" ]]; then
  if [[ "$output_mode" == "json" ]]; then
    printf '{"guard":[],"eval":[],"skill_proposal":[]}\n'
  else
    echo "[Maintenance] No tasks/lessons.md found."
  fi
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "[Maintenance] jq is required for maintenance triage." >&2
  exit 1
fi

lessons_json="$(
  awk '
    BEGIN {
      count = 0
      theme = ""
      prevention = ""
      trigger = ""
      current_field = ""
    }
    function escape_json(value) {
      gsub(/\\/, "\\\\", value)
      gsub(/"/, "\\\"", value)
      gsub(/\t/, "\\t", value)
      gsub(/\r/, "\\r", value)
      return value
    }
    function emit() {
      if (theme == "" && prevention == "") {
        return
      }
      count++
      printf "%s{\"theme\":\"%s\",\"prevention\":\"%s\",\"trigger\":\"%s\"}", (count > 1 ? "," : ""), escape_json(theme), escape_json(prevention), escape_json(trigger)
      theme = ""
      prevention = ""
      trigger = ""
      current_field = ""
    }
    /^- Date:/ {
      emit()
      next
    }
    /^- Mistake pattern:/ {
      theme = $0
      sub(/^- Mistake pattern:[[:space:]]*/, "", theme)
      current_field = "theme"
      next
    }
    /^- Prevention rule:/ {
      prevention = $0
      sub(/^- Prevention rule:[[:space:]]*/, "", prevention)
      current_field = "prevention"
      next
    }
    /^- Triggered by correction:/ {
      trigger = $0
      sub(/^- Triggered by correction:[[:space:]]*/, "", trigger)
      current_field = "trigger"
      next
    }
    /^- [A-Za-z]/ {
      current_field = ""
      next
    }
    {
      if (current_field == "theme" && $0 != "") {
        theme = theme "\\n" $0
      } else if (current_field == "prevention" && $0 != "") {
        prevention = prevention "\\n" $0
      } else if (current_field == "trigger" && $0 != "") {
        trigger = trigger "\\n" $0
      }
    }
    END {
      emit()
    }
  ' tasks/lessons.md
)"

if [[ -z "$lessons_json" ]]; then
  if [[ "$output_mode" == "json" ]]; then
    printf '{"guard":[],"eval":[],"skill_proposal":[]}\n'
  else
    echo "[Maintenance] No repeated lessons to triage."
  fi
  exit 0
fi

triage_json="$(
  jq -nc --argjson items "[${lessons_json}]" '
    def keyify:
      ascii_downcase | gsub("[^a-z0-9]+"; "-") | gsub("^-+|-+$"; "");
    def candidate_type(theme; count):
      if count >= 3 and (theme | test("guard|contract|plan|todo|sync|handoff|policy|workflow"; "i")) then "guard"
      elif count >= 2 and (theme | test("test|verify|eval|review|qa|assert"; "i")) then "eval"
      elif count >= 3 then "skill_proposal"
      else empty
      end;
    reduce $items[] as $item (
      {grouped:{}};
      .grouped[$item.theme|keyify] += [$item]
    )
    | .grouped
    | to_entries
    | map({
        key: .key,
        theme: (.value[0].theme // .key),
        count: (.value | length),
        candidate: candidate_type((.value[0].theme // .key); (.value | length))
      })
    | reduce .[] as $entry (
        {guard:[], eval:[], skill_proposal:[]};
        if ($entry.candidate // "") != "" then
          .[$entry.candidate] += [{
            key: $entry.key,
            theme: $entry.theme,
            count: $entry.count
          }]
        else .
        end
      )
  '
)"

if [[ "$output_mode" == "json" ]]; then
  printf '%s\n' "$triage_json"
  exit 0
fi

echo "[Maintenance] Guard candidates:"
jq -r '.guard[]? | "- \(.theme) (\(.count))"' <<< "$triage_json"
echo "[Maintenance] Eval candidates:"
jq -r '.eval[]? | "- \(.theme) (\(.count))"' <<< "$triage_json"
echo "[Maintenance] Skill proposal candidates:"
jq -r '.skill_proposal[]? | "- \(.theme) (\(.count))"' <<< "$triage_json"
