import { afterAll, describe, expect, test } from 'bun:test';
import { createHash } from 'crypto';
import { execFileSync } from 'child_process';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { refactorResolutionEvidenceDigest, type RecommendationV3, type RefactorResolutionEvidenceV1, type RefactorVerificationRequestV1 } from 'archctx-contracts';

import { sealProgramAuthorization } from '../../src/core/automation/budget';
import { buildRefactorCandidateVerificationReceipt } from '../../src/core/refactor/candidate-verification';
import { buildRefactorExecutionBinding } from '../../src/core/refactor/execution-binding';
import { buildRefactorProgram } from '../../src/core/refactor/program';
import { buildRefactorProgramDefinition } from '../../src/core/refactor/program-state';
import { RefactorProviderError } from '../../src/core/refactor/provider-contract';
import { mintProgramAuthorization } from '../../src/effects/automation/grant-store';
import { resolveRefactorPostMerge } from '../../src/effects/refactor/post-merge-resolution';
import { appendRefactorProgramEvent, createRefactorProgram, readRefactorProgramStatus } from '../../src/effects/refactor/program-store';
import { activateRefactorFixture } from '../helpers/refactor-activation-fixture';

const roots: string[] = []; const D = (value: string) => `sha256:${createHash('sha256').update(value).digest('hex')}`; const H = (value: string) => createHash('sha256').update(value).digest('hex'); const TASK = '9'.repeat(64); const TASK_REV = '8'.repeat(64); const NOW = '2026-09-04T06:00:00.000Z';
const limits = { max_agent_turns: 10, max_successful_acquisitions: 3, max_runner_invocations: 10, max_provider_failures: 3, max_consecutive_no_progress_steps: 2, max_repair_cycles: 2, max_wall_clock_seconds: 3600, max_input_tokens: null, max_output_tokens: null, max_cost_micros: null } as const;
function recommendation(status: RecommendationV3['status']): RecommendationV3 { return { schemaVersion: 'archcontext.recommendation/v3', recommendationId: 'recommendation.post', runId: 'run.post', fingerprint: D('recommendation'), subject: 'runtime.refactor', status, confidence: 'high', enforcement: 'advisory', risk: 'low', uncertainty: 'low', evidenceBindingIds: [], explanation: [], authoredBy: { kind: 'daemon', id: 'archctxd', source: 'daemon' }, subjectSelectorId: 'runtime.refactor', relations: {}, createdAt: NOW, updatedAt: NOW, category: 'structural_observation', payload: { assessmentDigest: D('assessment'), kind: 'cycle', affectedNodeIds: ['runtime.refactor'], baselineSnapshotDigest: D('stats'), derivedOutcomes: [] } }; }
function resolution(request: RefactorVerificationRequestV1, head: string, disposition: RefactorResolutionEvidenceV1['disposition']): RefactorResolutionEvidenceV1 { const basis = { schemaVersion: 'archcontext.refactor-resolution-evidence/v1' as const, recommendationId: 'recommendation.post', recommendationDigest: D('recommendation'), beforeSnapshotDigest: D('before'), afterSnapshotDigest: D('after'), verifiedHeadSha: head, verifiedWorktreeDigest: D('worktree'), expectedOutcomes: [], observedOutcomes: [], residuals: [], executionEvidenceRefs: request.executionEvidenceRefs ?? [], disposition, verifiedAt: NOW }; return { ...basis, resolutionDigest: refactorResolutionEvidenceDigest({ ...basis, resolutionDigest: D('placeholder') }) }; }
function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'refactor-post-merge-')); roots.push(root); const home = mkdtempSync(join(tmpdir(), 'refactor-post-home-')); roots.push(home); execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: root }); execFileSync('git', ['config', 'user.email', 'fixture@example.com'], { cwd: root }); execFileSync('git', ['config', 'user.name', 'Fixture'], { cwd: root });
  mkdirSync(join(root, 'plans'), { recursive: true }); mkdirSync(join(root, 'tasks', 'contracts'), { recursive: true }); mkdirSync(join(root, '.ai', 'harness'), { recursive: true }); writeFileSync(join(root, 'plans', 'plan.md'), '# Plan\n'); writeFileSync(join(root, 'tasks', 'contracts', 'task.md'), '# Contract\n'); writeFileSync(join(root, '.ai', 'harness', 'policy.json'), `${JSON.stringify({ refactor: { mode: 'active' } })}\n`); execFileSync('git', ['add', '.'], { cwd: root }); execFileSync('git', ['commit', '-qm', 'candidate'], { cwd: root }); const candidateHead = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
  const env = { ...process.env, REPO_HARNESS_HOME: home }; activateRefactorFixture(root, 'repo_0123456789abcdef', candidateHead, 'active_module'); const authorization = sealProgramAuthorization({ authorization_id: 'authorization-post', repository_id: 'repo_0123456789abcdef', target_ref: 'refs/heads/main', target_revision: candidateHead, work_graph_revision: H('graph'), allowed_work_package_ids: ['rf-post'], allowed_risk_tiers: ['low'], merge_mode: 'disabled', allowed_merge_method: 'squash', max_repair_cycles: 2, budget: limits, contract_scope: 'contract_less', contract_path: null, campaign: null, issued_by: 'owner', issued_at: NOW, expires_at: '2027-09-04T00:00:00.000Z' }); mintProgramAuthorization({ repo_root: root, authorization, env });
  const definition = buildRefactorProgramDefinition({ program_id: 'rf-post', authorization_id: authorization.authorization_id, authorization_sha256: authorization.authorization_sha256, repository_id: authorization.repository_id, target_ref: authorization.target_ref, target_revision: candidateHead, base_main_sha: candidateHead, created_at: NOW }); let current = createRefactorProgram({ repo_root: root, program: definition, idempotency_key: 'create', env }).current; for (const [index, operation] of (['begin_scan', 'observe', 'begin_authoring', 'assess', 'begin_route', 'begin_materialize', 'begin_plan', 'begin_execute', 'begin_verify'] as const).entries()) current = appendRefactorProgramEvent({ repo_root: root, program_id: 'rf-post', expected_current_sha256: current.current_sha256, idempotency_key: `step-${index}`, operation, observed_at: NOW, env }).current;
  execFileSync('git', ['commit', '--allow-empty', '-qm', 'merge'], { cwd: root }); const merge = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim(); const program = buildRefactorProgram({ programId: 'rf-post', baseMainSha: candidateHead, providerStage: 'scan', statisticsSnapshotDigest: D('stats'), assessmentDigest: D('assessment'), proposalDigest: D('proposal'), proposalAuthor: { kind: 'developer', source: 'manual' }, scale: 'module', routeReasonCodes: ['single-node-scope'], majorChangeReasons: [], route: 'module_refactor', affectedNodeIds: ['runtime.refactor'], bindings: [{ recommendationId: 'recommendation.post', recommendationDigest: D('recommendation'), candidateAlias: 'C01', workPackageId: 'rf-post', taskRef: `plans/sprints/rf.sprint.md#${TASK}`, executionBoundary: 'module' }] });
  const candidate = buildRefactorCandidateVerificationReceipt({ recommendationId: 'recommendation.post', recommendationDigest: D('recommendation'), candidateHeadSha: candidateHead, candidateWorktreeDigest: D('candidate-worktree'), taskId: TASK, taskRevision: TASK_REV, contractPath: 'tasks/contracts/task.md', contractSha256: D('# Contract\n'), contractVerificationSha256: D('verify'), cutoverClosureLocator: '.ai/harness/checks/closure.json', cutoverClosureSha256: D('closure'), candidateVerify: 'passed', candidateVerifyResultSha256: D('candidate-verify'), acceptanceReceiptSha256: D('acceptance') }); const binding = buildRefactorExecutionBinding({ recommendationId: 'recommendation.post', recommendationDigest: D('recommendation'), taskId: TASK, taskRevision: TASK_REV, planPath: 'plans/plan.md', planSha256: D('# Plan\n'), contractPath: 'tasks/contracts/task.md', contractSha256: D('# Contract\n'), cutoverClosureSha256: D('closure'), acceptanceReceiptSha256: D('acceptance'), pullRequestNumber: 9, pullRequestHeadSha: candidateHead, mergeCommitSha: merge }); return { root, home, env, current, merge, program, candidate, binding };
}
afterAll(() => roots.forEach((root) => rmSync(root, { recursive: true, force: true })));
describe('Module 9 exact post-merge resolution', () => {
  test('records ArchContext resolution and completes only after exact final-main evidence', async () => { const f = fixture(); const order: string[] = [];
    let resolved = false; const dependencies = { verify: (request: RefactorVerificationRequestV1) => { order.push('verify'); const evidence = resolution(request, f.merge, 'resolved'); return { disposition: 'resolved', evidence } as never; }, resolve: () => { order.push('resolve'); resolved = true; }, recommendations: () => { order.push('recommendations'); return [recommendation(resolved ? 'resolved' : 'accepted')]; } };
    const request = { repo_root: f.root, program: f.program, final_main_sha: f.merge, final_worktree_digest: D('worktree'), items: [{ candidateVerification: f.candidate, binding: f.binding, acceptanceReceiptLocator: '.repo-harness/acceptance.json', mergeReceiptLocator: '.repo-harness/merge.json', mergeReceiptSha256: D('merge') }], expected_current_sha256: f.current.current_sha256, idempotency_key: 'post', observed_at: NOW, env: f.env } as const;
    const result = await resolveRefactorPostMerge(request, dependencies); expect(order).toEqual(['verify', 'recommendations', 'resolve', 'recommendations']); expect(result.stage).toBe('resolved'); expect(readRefactorProgramStatus(f.root, 'rf-post', f.env).current.state).toBe('complete'); expect(existsSync(result.jsonPath)).toBe(true); expect(readFileSync(result.markdownPath, 'utf8')).toContain('resolved (resolved)');
    order.length = 0; expect((await resolveRefactorPostMerge({ ...request, expected_current_sha256: readRefactorProgramStatus(f.root, 'rf-post', f.env).current.current_sha256 }, dependencies)).stage).toBe('resolved'); expect(order).toEqual(['recommendations']);
  });
  test('Stage 2 absence stays merged_pending_measurement and never claims resolution', async () => { const f = fixture(); const result = await resolveRefactorPostMerge({ repo_root: f.root, program: f.program, final_main_sha: f.merge, final_worktree_digest: D('worktree'), items: [{ candidateVerification: f.candidate, binding: f.binding, acceptanceReceiptLocator: '.repo-harness/acceptance.json', mergeReceiptLocator: '.repo-harness/merge.json', mergeReceiptSha256: D('merge') }], expected_current_sha256: f.current.current_sha256, idempotency_key: 'post', observed_at: NOW, env: f.env }, { verify: () => { throw new RefactorProviderError('refactor_provider_version_mismatch', 'missing'); }, recommendations: () => [recommendation('accepted')] }); expect(result.stage).toBe('merged_pending_measurement'); expect(result.board.cards[0]?.architectureResult).toBe('merged_pending_measurement'); expect(readRefactorProgramStatus(f.root, 'rf-post', f.env).current.state).toBe('post_merge_measuring'); });
});
